### ISSUE TITLE
Features : Backgrounds should be generated as @Before blocks

### ISSUE THREAD

**Issue by ghaith** [riederm/Jnario#6]
When defining a feature, a Background block is currently getting its own class with a @Test annotation on it and then is added to each Scenario as a @Test method with order 0, this is effectively a @Before block and should be genrated as such

**Comment by riederm** [comment]
I may be wrong, but isnt like a @Before executed before every single @Test?
while the Background is meant to be executed once per scenario?

**Comment by ghaith** [comment]
You're right I kind of missed that, I was thinking of 1 test per scenario
for some reason but that's obviously wrong

**Comment by riederm** [comment]
so ill close this
